### ISSUE TITLE
Can't compile if package version is 2021

### ISSUE THREAD

**Issue by myOmikron** [agavrilov/rust-cross-compile-x86_64#3]
Cargo.toml:
```
[package]
name = "osx-cross-test"
version = "0.1.0"
edition = "2021"
```
No dependencies are listed.

The following error occurs:
```
error: failed to parse manifest at `/work/Cargo.toml`

Caused by:
  feature `edition2021` is required

  this Cargo does not support nightly features, but if you
  switch to nightly channel you can add
  `cargo-features = ["edition2021"]` to enable this feature
```

This also happens with any dependencies that are on the edition `2021`

**Comment by agavrilov** [comment]
Docker image in Docker Hub is not updated anymore. I moved the image to GitHub registry. Please, try to use a new image from GitHub: `ghcr.io/agavrilov/rust-cross-compile-x86_64:1.65.0`. I'll update README to avoid confusion

**Comment by myOmikron** [comment]
Thanks, that worked like  a charm
